STDLIB_SIGS = [[[:BasicObject], [:Object], [], []],
 [[:Object],
  [:Object],
  [[:freeze, [[[], [], nil, [:self]]]],
   [:nil?, [[[], [], nil, [:bool]]]],
   [:to_s, [[[], [], nil, [:instance, [:String]]]]],
   [:fail,
    [[[], [], nil, [:union, []]],
     [[[:instance, [:String]]], [], nil, [:union, []]],
     [[],
      [[:instance, [:Exception]],
       [:instance, [:String]],
       [:instance, [:Array]]],
      nil,
      [:union, []]]]],
   [:loop,
    [[[], [], [[], [:any]], [:union, []]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:rand,
    [[[], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Float]]]]],
   [:block_given?, [[[], [], nil, [:bool]]]],
   [:kind_of?, [[[[:instance, [:Module]]], [], nil, [:bool]]]],
   [:respond_to?,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [[:bool]],
      nil,
      [:bool]]]]],
  []],
 [[:Fiber], [:Object], [], []],
 [[:Array],
  [:Object],
  [[:empty?, [[[], [], nil, [:bool]]]],
   [:size, [[[], [], nil, [:instance, [:Integer]]]]]],
  []],
 [[:Enumerable], [:Object], [], []],
 [[:Range], [:Object], [], []],
 [[:Method], [:Object], [], []],
 [[:Numeric],
  [:Object],
  [[:step,
    [[[],
      [[:instance, [:Numeric]], [:instance, [:Numeric]]],
      [[[:instance, [:Numeric]]], [:any]],
      [:self]],
     [[],
      [[:instance, [:Numeric]], [:instance, [:Numeric]]],
      nil,
      [:instance, [:Enumerator]]],
     [[], [], [[[:instance, [:Numeric]]], [:any]], [:self]],
     [[], [], nil, [:instance, [:Enumerator]]]]]],
  []],
 [[:Rational], [:Numeric], [], []],
 [[:Complex], [:Numeric], [], []],
 [[:String], [:Object], [], []],
 [[:Struct], [:Object], [], []],
 [[:Exception], [:Object], [], []],
 [[:StandardError], [:Exception], [], []],
 [[:FiberError], [:StandardError], [], []],
 [[:TracePoint], [:Object], [], []],
 [[:FalseClass], [:Object], [[:!, [[[], [], nil, [:bool]]]]], []],
 [[:Kernel], [:Object], [], []],
 [[:Binding], [:Object], [], []],
 [[:StringIO], [:Object], [], []],
 [[:Data], [:Object], [], []],
 [[:Encoding], [:Object], [], []],
 [[:EncodingError], [:StandardError], [], []],
 [[:Encoding, :UndefinedConversionError], [:EncodingError], [], []],
 [[:Encoding, :InvalidByteSequenceError], [:EncodingError], [], []],
 [[:Encoding, :ConverterNotFoundError], [:EncodingError], [], []],
 [[:Encoding, :CompatibilityError], [:EncodingError], [], []],
 [[:Encoding, :Converter], [:Data], [], []],
 [[:Process], [:Object], [], []],
 [[:Thread], [:Object], [], []],
 [[:Process, :Waiter], [:Thread], [], []],
 [[:Process, :Tms], [:Struct], [], []],
 [[:Process, :UID], [:Object], [], []],
 [[:Process, :Sys], [:Object], [], []],
 [[:Process, :Status], [:Object], [], []],
 [[:Process, :GID], [:Object], [], []],
 [[:NilClass], [:Object], [], []],
 [[:Marshal], [:Object], [], []],
 [[:Regexp], [:Object], [], []],
 [[:Module], [:Object], [], []],
 [[:Hash], [:Object], [], []],
 [[:Enumerator], [:Object], [], []],
 [[:Enumerator, :Chain], [:Object], [], []],
 [[:Enumerator, :Yielder], [:Object], [], []],
 [[:Enumerator, :Lazy], [:Enumerator], [], []],
 [[:Enumerator, :Generator], [:Object], [], []],
 [[:Integer],
  [:Numeric],
  [[:!, [[[], [], nil, [:bool]]]],
   [:!=, [[[[:any]], [], nil, [:bool]]]],
   [:==, [[[[:any]], [], nil, [:bool]]]],
   [:__id__, [[[], [], nil, [:instance, [:Integer]]]]],
   [:__send__,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]]],
      [],
      nil,
      [:any]]]],
   [:equal?, [[[[:any]], [], nil, [:bool]]]],
   [:instance_eval,
    [[[[:instance, [:String]]],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:any]],
     [[], [], [[[:self]], [:any]], [:any]]]],
   [:instance_exec, [[[], [], [[], [:any]], [:any]]]],
   [:initialize, [[[], [], nil, [:any]]]],
   [:method_missing, [[[[:instance, [:Symbol]]], [], nil, [:any]]]],
   [:singleton_method_added, [[[[:instance, [:Symbol]]], [], nil, [:any]]]],
   [:singleton_method_removed, [[[[:instance, [:Symbol]]], [], nil, [:any]]]],
   [:singleton_method_undefined,
    [[[[:instance, [:Symbol]]], [], nil, [:any]]]],
   [:caller,
    [[[],
      [[:instance, [:Integer]], [:instance, [:Integer]]],
      nil,
      [:optional, [:instance, [:Array]]]],
     [[], [[:instance, [:Range]]], nil, [:optional, [:instance, [:Array]]]],
     [[], [], nil, [:instance, [:Array]]]]],
   [:caller_locations,
    [[[],
      [[:instance, [:Integer]], [:instance, [:Integer]]],
      nil,
      [:optional, [:instance, [:Array]]]],
     [[], [[:instance, [:Range]]], nil, [:optional, [:instance, [:Array]]]]]],
   [:catch,
    [[[[:any]], [], [[[:any]], [:any]], [:any]],
     [[], [], [[[:instance, [:Object]]], [:any]], [:any]]]],
   [:define_singleton_method,
    [[[[:instance, [:Symbol]],
       [:union, [[:instance, [:Method]], [:instance, [:UnboundMethod]]]]],
      [],
      nil,
      [:instance, [:Symbol]]],
     [[[:instance, [:Symbol]]], [], [[], [:any]], [:instance, [:Symbol]]]]],
   [:eval,
    [[[[:instance, [:String]]],
      [[:instance, [:Binding]],
       [:instance, [:String]],
       [:instance, [:Integer]]],
      nil,
      [:any]]]],
   [:iterator?, [[[], [], nil, [:bool]]]],
   [:local_variables, [[[], [], nil, [:instance, [:Array]]]]],
   [:srand, [[[], [[:instance, [:Numeric]]], nil, [:instance, [:Numeric]]]]],
   [:!~, [[[[:any]], [], nil, [:bool]]]],
   [:<=>,
    [[[[:instance, [:Numeric]]],
      [],
      nil,
      [:optional, [:instance, [:Integer]]]]]],
   [:===, [[[[:any]], [], nil, [:bool]]]],
   [:=~, [[[[:any]], [], nil, [:bool]]]],
   [:clone, [[[], [], nil, [:self]]]],
   [:display, [[[], [[:any]], nil, [:any]]]],
   [:dup, [[[], [], nil, [:self]]]],
   [:enum_for,
    [[[[:instance, [:Symbol]]],
      [],
      [[], [:instance, [:Integer]]],
      [:instance, [:Enumerator]]],
     [[], [], [[], [:instance, [:Integer]]], [:instance, [:Enumerator]]]]],
   [:eql?, [[[[:any]], [], nil, [:bool]]]],
   [:extend, [[[], [], nil, [:self]]]],
   [:fork,
    [[[], [], nil, [:optional, [:instance, [:Integer]]]],
     [[], [], [[], [:any]], [:optional, [:instance, [:Integer]]]]]],
   [:freeze, [[[], [], nil, [:self]]]],
   [:frozen?, [[[], [], nil, [:bool]]]],
   [:hash, [[[], [], nil, [:instance, [:Integer]]]]],
   [:initialize_copy, [[[[:self]], [], nil, [:self]]]],
   [:inspect,
    [[[], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:instance, [:String]]]]],
   [:instance_of?, [[[[:instance, [:Module]]], [], nil, [:bool]]]],
   [:instance_variable_defined?,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]]],
      [],
      nil,
      [:bool]]]],
   [:instance_variable_get,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]]],
      [],
      nil,
      [:any]]]],
   [:instance_variable_set,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]], [:any]],
      [],
      nil,
      [:any]]]],
   [:instance_variables, [[[], [], nil, [:instance, [:Array]]]]],
   [:is_a?, [[[[:instance, [:Module]]], [], nil, [:bool]]]],
   [:method,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]]],
      [],
      nil,
      [:instance, [:Method]]]]],
   [:methods, [[[], [], nil, [:instance, [:Array]]]]],
   [:nil?, [[[], [], nil, [:bool]]]],
   [:private_methods, [[[], [], nil, [:instance, [:Array]]]]],
   [:protected_methods, [[[], [], nil, [:instance, [:Array]]]]],
   [:public_method,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      nil,
      [:instance, [:Method]]]]],
   [:public_methods, [[[], [[:bool]], nil, [:instance, [:Array]]]]],
   [:public_send,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      [[], [:any]],
      [:any]]]],
   [:remove_instance_variable,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      nil,
      [:any]]]],
   [:send,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      [[], [:any]],
      [:any]]]],
   [:singleton_class, [[[], [], nil, [:instance, [:Class]]]]],
   [:singleton_method,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      nil,
      [:instance, [:Method]]]]],
   [:singleton_methods, [[[], [], nil, [:instance, [:Array]]]]],
   [:taint, [[[], [], nil, [:self]]]],
   [:tainted?, [[[], [], nil, [:bool]]]],
   [:tap, [[[], [], [[[:self]], [:any]], [:self]]]],
   [:to_s,
    [[[], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:int]], [], nil, [:instance, [:String]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:instance, [:String]]]]],
   [:untaint, [[[], [], nil, [:self]]]],
   [:Array,
    [[[[:instance, [:NilClass]]], [], nil, [:array, [], [:union, []]]],
     [[[:instance, [:Array]]], [], nil, [:instance, [:Array]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Array]]],
     [[[:instance, [:Hash]]], [], nil, [:instance, [:Array]]],
     [[[:any]], [], nil, [:instance, [:Array]]]]],
   [:Complex,
    [[[[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      [[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      nil,
      [:instance, [:Complex]]]]],
   [:Float,
    [[[[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      [],
      nil,
      [:instance, [:Float]]]]],
   [:Hash, [[[[:instance, [:Object]]], [], nil, [:instance, [:Hash]]]]],
   [:Integer,
    [[[[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      [],
      nil,
      [:instance, [:Integer]]],
     [[[:instance, [:String]]],
      [[:instance, [:Integer]]],
      nil,
      [:instance, [:Integer]]]]],
   [:Rational,
    [[[[:union,
        [[:instance, [:Numeric]],
         [:instance, [:String]],
         [:instance, [:Object]]]]],
      [[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      nil,
      [:instance, [:Rational]]]]],
   [:String, [[[[:instance, [:Object]]], [], nil, [:instance, [:String]]]]],
   [:__callee__, [[[], [], nil, [:optional, [:instance, [:Symbol]]]]]],
   [:__dir__, [[[], [], nil, [:optional, [:instance, [:String]]]]]],
   [:__method__, [[[], [], nil, [:optional, [:instance, [:Symbol]]]]]],
   [:`, [[[[:instance, [:String]]], [], nil, [:instance, [:String]]]]],
   [:abort, [[[], [[:instance, [:String]]], nil, [:union, []]]]],
   [:at_exit, [[[], [], [[], [:any]], [:instance, [:Proc]]]]],
   [:autoload,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]],
       [:instance, [:String]]],
      [],
      nil,
      [:instance, [:NilClass]]]]],
   [:autoload?,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      nil,
      [:optional, [:instance, [:String]]]]]],
   [:binding, [[[], [], nil, [:instance, [:Binding]]]]],
   [:exit,
    [[[], [], nil, [:union, []]],
     [[],
      [[:union,
        [[:instance, [:Integer]],
         [:instance, [:TrueClass]],
         [:instance, [:FalseClass]]]]],
      nil,
      [:union, []]]]],
   [:exit!,
    [[[[:union,
        [[:instance, [:Integer]],
         [:instance, [:TrueClass]],
         [:instance, [:FalseClass]]]]],
      [],
      nil,
      [:union, []]]]],
   [:fail,
    [[[], [], nil, [:union, []]],
     [[[:instance, [:String]]], [], nil, [:union, []]],
     [[],
      [[:instance, [:Exception]],
       [:instance, [:String]],
       [:instance, [:Array]]],
      nil,
      [:union, []]]]],
   [:format, [[[[:instance, [:String]]], [], nil, [:instance, [:String]]]]],
   [:gets,
    [[[],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:optional, [:instance, [:String]]]]]],
   [:global_variables, [[[], [], nil, [:instance, [:Array]]]]],
   [:load, [[[[:instance, [:String]]], [[:bool]], nil, [:bool]]]],
   [:loop,
    [[[], [], [[], [:any]], [:union, []]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:open,
    [[[[:instance, [:String]]],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:optional, [:instance, [:IO]]]],
     [[[:instance, [:String]]],
      [[:instance, [:String]], [:instance, [:Integer]]],
      [[[:instance, [:IO]]], [:any]],
      [:any]]]],
   [:print, [[[], [], nil, [:nil]]]],
   [:printf,
    [[[], [[:instance, [:IO]], [:instance, [:String]]], nil, [:nil]]]],
   [:proc, [[[], [], [[], [:any]], [:instance, [:Proc]]]]],
   [:lambda, [[[], [], [[], [:any]], [:instance, [:Proc]]]]],
   [:putc,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:String]]], [], nil, [:instance, [:String]]]]],
   [:puts, [[[], [], nil, [:instance, [:NilClass]]]]],
   [:p, [[[[:any]], [], nil, [:any]], [[], [], nil, [:instance, [:Array]]]]],
   [:pp, [[[[:any]], [], nil, [:any]], [[], [], nil, [:instance, [:Array]]]]],
   [:rand,
    [[[], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Float]]]]],
   [:readline,
    [[[],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:instance, [:String]]]]],
   [:readlines,
    [[[],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:instance, [:Array]]]]],
   [:require, [[[[:instance, [:String]]], [], nil, [:bool]]]],
   [:require_relative, [[[[:instance, [:String]]], [], nil, [:bool]]]],
   [:select,
    [[[[:instance, [:Array]]],
      [[:instance, [:Array]], [:instance, [:Array]], [:instance, [:Integer]]],
      nil,
      [:instance, [:Array]]]]],
   [:sleep,
    [[[], [], nil, [:union, []]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Integer]]]]],
   [:syscall, [[[[:instance, [:Integer]]], [], nil, [:any]]]],
   [:test,
    [[[[:union, [[:instance, [:String]], [:instance, [:Integer]]]],
       [:union, [[:instance, [:String]], [:instance, [:IO]]]]],
      [[:union, [[:instance, [:String]], [:instance, [:IO]]]]],
      nil,
      [:union,
       [[:instance, [:TrueClass]],
        [:instance, [:FalseClass]],
        [:instance, [:Time]],
        [:nil],
        [:instance, [:Integer]]]]]]],
   [:throw, [[[[:instance, [:Object]]], [[:any]], nil, [:union, []]]]],
   [:warn, [[[], [], nil, [:instance, [:NilClass]]]]],
   [:exec, [[[], [], nil, [:union, []]]]],
   [:system,
    [[[],
      [],
      nil,
      [:union,
       [[:instance, [:NilClass]],
        [:instance, [:FalseClass]],
        [:instance, [:TrueClass]]]]]]],
   [:block_given?, [[[], [], nil, [:bool]]]],
   [:to_enum,
    [[[[:instance, [:Symbol]]],
      [],
      [[], [:instance, [:Integer]]],
      [:instance, [:Enumerator]]],
     [[], [], [[], [:instance, [:Integer]]], [:instance, [:Enumerator]]]]],
   [:kind_of?, [[[[:instance, [:Module]]], [], nil, [:bool]]]],
   [:untrust, [[[], [], nil, [:self]]]],
   [:untrusted?, [[[], [], nil, [:bool]]]],
   [:trust, [[[], [], nil, [:self]]]],
   [:raise,
    [[[], [], nil, [:union, []]],
     [[[:instance, [:String]]], [], nil, [:union, []]],
     [[],
      [[:instance, [:Exception]],
       [:instance, [:String]],
       [:instance, [:Array]]],
      nil,
      [:union, []]]]],
   [:sprintf, [[[[:instance, [:String]]], [], nil, [:instance, [:String]]]]],
   [:itself, [[[], [], nil, [:self]]]],
   [:object_id, [[[], [], nil, [:instance, [:Integer]]]]],
   [:respond_to?,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [[:bool]],
      nil,
      [:bool]]]],
   [:yield_self,
    [[[], [], [[[:self]], [:any]], [:any]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:then,
    [[[], [], [[[:self]], [:any]], [:any]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:<, [[[[:instance, [:Numeric]]], [], nil, [:bool]]]],
   [:<=, [[[[:instance, [:Numeric]]], [], nil, [:bool]]]],
   [:>, [[[[:instance, [:Numeric]]], [], nil, [:bool]]]],
   [:>=, [[[[:instance, [:Numeric]]], [], nil, [:bool]]]],
   [:between?, [[[[:any], [:any]], [], nil, [:bool]]]],
   [:clamp, [[[[:any], [:any]], [], nil, [:any]]]],
   [:%,
    [[[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]]]],
   [:+@, [[[], [], nil, [:instance, [:Integer]]]]],
   [:-@, [[[], [], nil, [:instance, [:Integer]]]]],
   [:abs, [[[], [], nil, [:instance, [:Integer]]]]],
   [:abs2, [[[], [], nil, [:instance, [:Integer]]]]],
   [:angle,
    [[[],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:ceil,
    [[[], [], nil, [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:coerce,
    [[[[:instance, [:Numeric]]],
      [],
      nil,
      [:array,
       [[:instance, [:Numeric]], [:instance, [:Numeric]]],
       [:union, []]]]]],
   [:conj, [[[], [], nil, [:instance, [:Integer]]]]],
   [:conjugate, [[[], [], nil, [:instance, [:Integer]]]]],
   [:denominator, [[[], [], nil, [:instance, [:Integer]]]]],
   [:div, [[[[:instance, [:Numeric]]], [], nil, [:instance, [:Integer]]]]],
   [:divmod,
    [[[[:instance, [:Integer]]],
      [],
      nil,
      [:array,
       [[:instance, [:Integer]], [:instance, [:Integer]]],
       [:union, []]]],
     [[[:instance, [:Float]]],
      [],
      nil,
      [:array, [[:instance, [:Float]], [:instance, [:Float]]], [:union, []]]],
     [[[:instance, [:Numeric]]],
      [],
      nil,
      [:array,
       [[:instance, [:Numeric]], [:instance, [:Numeric]]],
       [:union, []]]]]],
   [:fdiv, [[[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:finite?, [[[], [], nil, [:bool]]]],
   [:floor,
    [[[], [], nil, [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:i, [[[], [], nil, [:instance, [:Complex]]]]],
   [:imag, [[[], [], nil, [:instance, [:Integer]]]]],
   [:imaginary, [[[], [], nil, [:instance, [:Integer]]]]],
   [:infinite?, [[[], [], nil, [:optional, [:instance, [:Integer]]]]]],
   [:integer?, [[[], [], nil, [:true]]]],
   [:modulo,
    [[[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]]]],
   [:negative?, [[[], [], nil, [:bool]]]],
   [:nonzero?, [[[], [], nil, [:optional, [:self]]]]],
   [:numerator, [[[], [], nil, [:instance, [:Integer]]]]],
   [:polar,
    [[[],
      [],
      nil,
      [:array,
       [[:instance, [:Integer]],
        [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]],
       [:union, []]]]]],
   [:positive?, [[[], [], nil, [:bool]]]],
   [:quo,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Numeric]]]]],
   [:real, [[[], [], nil, [:self]]]],
   [:real?, [[[], [], nil, [:true]]]],
   [:rect,
    [[[],
      [],
      nil,
      [:array,
       [[:instance, [:Integer]], [:instance, [:Numeric]]],
       [:union, []]]]]],
   [:remainder,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Numeric]]]]],
   [:round,
    [[[], [], nil, [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:step,
    [[[], [], [[[:instance, [:Integer]]], [:any]], [:self]],
     [[[:instance, [:Numeric]]],
      [[:instance, [:Integer]]],
      [[[:instance, [:Integer]]], [:any]],
      [:self]],
     [[[:instance, [:Numeric]]],
      [[:instance, [:Numeric]]],
      [[[:instance, [:Numeric]]], [:any]],
      [:self]],
     [[], [], [[[:instance, [:Integer]]], [:any]], [:self]],
     [[], [], [[[:instance, [:Numeric]]], [:any]], [:self]],
     [[], [], nil, [:instance, [:Enumerator]]],
     [[[:instance, [:Numeric]]],
      [[:instance, [:Integer]]],
      nil,
      [:instance, [:Enumerator]]],
     [[[:instance, [:Numeric]]],
      [[:instance, [:Numeric]]],
      nil,
      [:instance, [:Enumerator]]],
     [[], [], nil, [:instance, [:Enumerator]]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:to_c, [[[], [], nil, [:instance, [:Complex]]]]],
   [:to_int, [[[], [], nil, [:instance, [:Integer]]]]],
   [:truncate,
    [[[], [], nil, [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:instance, [:Integer]]]]],
   [:zero?, [[[], [], nil, [:bool]]]],
   [:arg,
    [[[],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:magnitude, [[[], [], nil, [:instance, [:Integer]]]]],
   [:phase,
    [[[],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:rectangular,
    [[[],
      [],
      nil,
      [:array,
       [[:instance, [:Integer]], [:instance, [:Numeric]]],
       [:union, []]]]]],
   [:&, [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]]]],
   [:*,
    [[[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]]]],
   [:**,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Numeric]]],
     [[[:instance, [:Float]]], [], nil, [:instance, [:Numeric]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Numeric]]],
     [[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]]]],
   [:+,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]]]],
   [:-,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]]]],
   [:/,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Rational]]],
     [[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]]]],
   [:<<,
    [[[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:instance, [:Integer]]]]],
   [:>>,
    [[[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:instance, [:Integer]]]]],
   [:[],
    [[[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]],
       [:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:instance, [:Integer]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Integer]]]]],
   [:^, [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]]]],
   [:allbits?,
    [[[[:union, [[:instance, [:Integer]], [:any]]]], [], nil, [:bool]]]],
   [:anybits?,
    [[[[:union, [[:instance, [:Integer]], [:any]]]], [], nil, [:bool]]]],
   [:bit_length, [[[], [], nil, [:instance, [:Integer]]]]],
   [:chr,
    [[[],
      [[:union,
        [[:instance, [:Encoding]],
         [:union, [[:instance, [:String]], [:any]]]]]],
      nil,
      [:instance, [:String]]]]],
   [:digits,
    [[[],
      [[:union, [[:instance, [:Integer]], [:any]]]],
      nil,
      [:instance, [:Array]]]]],
   [:downto,
    [[[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      [[[:instance, [:Integer]]], [:any]],
      [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:instance, [:Enumerator]]]]],
   [:even?, [[[], [], nil, [:bool]]]],
   [:gcd, [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]]]],
   [:gcdlcm,
    [[[[:instance, [:Integer]]],
      [],
      nil,
      [:array,
       [[:instance, [:Integer]], [:instance, [:Integer]]],
       [:union, []]]]]],
   [:lcm, [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]]]],
   [:next, [[[], [], nil, [:instance, [:Integer]]]]],
   [:nobits?,
    [[[[:union, [[:instance, [:Integer]], [:any]]]], [], nil, [:bool]]]],
   [:odd?, [[[], [], nil, [:bool]]]],
   [:ord, [[[], [], nil, [:instance, [:Integer]]]]],
   [:pow,
    [[[[:instance, [:Integer]]],
      [[:instance, [:Integer]]],
      nil,
      [:instance, [:Integer]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Numeric]]]]],
   [:pred, [[[], [], nil, [:instance, [:Integer]]]]],
   [:rationalize,
    [[[], [[:instance, [:Numeric]]], nil, [:instance, [:Rational]]]]],
   [:size, [[[], [], nil, [:instance, [:Integer]]]]],
   [:succ, [[[], [], nil, [:instance, [:Integer]]]]],
   [:times,
    [[[], [], [[[:instance, [:Integer]]], [:any]], [:self]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:to_f, [[[], [], nil, [:instance, [:Float]]]]],
   [:to_i, [[[], [], nil, [:instance, [:Integer]]]]],
   [:to_r, [[[], [], nil, [:instance, [:Rational]]]]],
   [:upto,
    [[[[:instance, [:Integer]]],
      [],
      [[[:instance, [:Integer]]], [:any]],
      [:instance, [:Integer]]],
     [[[:instance, [:Integer]]], [], nil, [:instance, [:Enumerator]]]]],
   [:|, [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]]]],
   [:~, [[[], [], nil, [:instance, [:Integer]]]]]],
  []],
 [[:Class], [:Module], [], []],
 [[:ThreadGroup], [:Object], [], []],
 [[:Signal], [:Object], [], []],
 [[:RbConfig], [:Object], [], []],
 [[:Errno], [:Object], [], []],
 [[:SystemCallError], [:StandardError], [], []],
 [[:Errno, :NOERROR], [:SystemCallError], [], []],
 [[:Errno, :EXFULL], [:SystemCallError], [], []],
 [[:Errno, :EXDEV], [:SystemCallError], [], []],
 [[:Errno, :EUSERS], [:SystemCallError], [], []],
 [[:Errno, :EUNATCH], [:SystemCallError], [], []],
 [[:Errno, :EUCLEAN], [:SystemCallError], [], []],
 [[:Errno, :ETXTBSY], [:SystemCallError], [], []],
 [[:Errno, :ETOOMANYREFS], [:SystemCallError], [], []],
 [[:Errno, :ETIMEDOUT], [:SystemCallError], [], []],
 [[:Errno, :ETIME], [:SystemCallError], [], []],
 [[:Errno, :ESTRPIPE], [:SystemCallError], [], []],
 [[:Errno, :ESTALE], [:SystemCallError], [], []],
 [[:Errno, :ESRMNT], [:SystemCallError], [], []],
 [[:Errno, :ESRCH], [:SystemCallError], [], []],
 [[:Errno, :ESPIPE], [:SystemCallError], [], []],
 [[:Errno, :ESOCKTNOSUPPORT], [:SystemCallError], [], []],
 [[:Errno, :ESHUTDOWN], [:SystemCallError], [], []],
 [[:Errno, :EROFS], [:SystemCallError], [], []],
 [[:Errno, :ERFKILL], [:SystemCallError], [], []],
 [[:Errno, :ERESTART], [:SystemCallError], [], []],
 [[:Errno, :EREMOTEIO], [:SystemCallError], [], []],
 [[:Errno, :EREMOTE], [:SystemCallError], [], []],
 [[:Errno, :EREMCHG], [:SystemCallError], [], []],
 [[:Errno, :ERANGE], [:SystemCallError], [], []],
 [[:Errno, :EPROTOTYPE], [:SystemCallError], [], []],
 [[:Errno, :EPROTONOSUPPORT], [:SystemCallError], [], []],
 [[:Errno, :EPROTO], [:SystemCallError], [], []],
 [[:Errno, :EPIPE], [:SystemCallError], [], []],
 [[:Errno, :EPFNOSUPPORT], [:SystemCallError], [], []],
 [[:Errno, :EPERM], [:SystemCallError], [], []],
 [[:Errno, :EOWNERDEAD], [:SystemCallError], [], []],
 [[:Errno, :EOVERFLOW], [:SystemCallError], [], []],
 [[:Errno, :EOPNOTSUPP], [:SystemCallError], [], []],
 [[:Errno, :ENXIO], [:SystemCallError], [], []],
 [[:Errno, :ENOTUNIQ], [:SystemCallError], [], []],
 [[:Errno, :ENOTTY], [:SystemCallError], [], []],
 [[:Errno, :ENOTSOCK], [:SystemCallError], [], []],
 [[:Errno, :ENOTRECOVERABLE], [:SystemCallError], [], []],
 [[:Errno, :ENOTNAM], [:SystemCallError], [], []],
 [[:Errno, :ENOTEMPTY], [:SystemCallError], [], []],
 [[:Errno, :ENOTDIR], [:SystemCallError], [], []],
 [[:Errno, :ENOTCONN], [:SystemCallError], [], []],
 [[:Errno, :ENOTBLK], [:SystemCallError], [], []],
 [[:Errno, :ENOSYS], [:SystemCallError], [], []],
 [[:Errno, :ENOSTR], [:SystemCallError], [], []],
 [[:Errno, :ENOSR], [:SystemCallError], [], []],
 [[:Errno, :ENOSPC], [:SystemCallError], [], []],
 [[:Errno, :ENOPROTOOPT], [:SystemCallError], [], []],
 [[:Errno, :ENOPKG], [:SystemCallError], [], []],
 [[:Errno, :ENONET], [:SystemCallError], [], []],
 [[:Errno, :ENOMSG], [:SystemCallError], [], []],
 [[:Errno, :ENOMEM], [:SystemCallError], [], []],
 [[:Errno, :ENOMEDIUM], [:SystemCallError], [], []],
 [[:Errno, :ENOLINK], [:SystemCallError], [], []],
 [[:Errno, :ENOLCK], [:SystemCallError], [], []],
 [[:Errno, :ENOKEY], [:SystemCallError], [], []],
 [[:Errno, :ENOEXEC], [:SystemCallError], [], []],
 [[:Errno, :ENOENT], [:SystemCallError], [], []],
 [[:Errno, :ENODEV], [:SystemCallError], [], []],
 [[:Errno, :ENODATA], [:SystemCallError], [], []],
 [[:Errno, :ENOCSI], [:SystemCallError], [], []],
 [[:Errno, :ENOBUFS], [:SystemCallError], [], []],
 [[:Errno, :ENOANO], [:SystemCallError], [], []],
 [[:Errno, :ENFILE], [:SystemCallError], [], []],
 [[:Errno, :ENETUNREACH], [:SystemCallError], [], []],
 [[:Errno, :ENETRESET], [:SystemCallError], [], []],
 [[:Errno, :ENETDOWN], [:SystemCallError], [], []],
 [[:Errno, :ENAVAIL], [:SystemCallError], [], []],
 [[:Errno, :ENAMETOOLONG], [:SystemCallError], [], []],
 [[:Errno, :EMULTIHOP], [:SystemCallError], [], []],
 [[:Errno, :EMSGSIZE], [:SystemCallError], [], []],
 [[:Errno, :EMLINK], [:SystemCallError], [], []],
 [[:Errno, :EMFILE], [:SystemCallError], [], []],
 [[:Errno, :EMEDIUMTYPE], [:SystemCallError], [], []],
 [[:Errno, :ELOOP], [:SystemCallError], [], []],
 [[:Errno, :ELNRNG], [:SystemCallError], [], []],
 [[:Errno, :ELIBSCN], [:SystemCallError], [], []],
 [[:Errno, :ELIBMAX], [:SystemCallError], [], []],
 [[:Errno, :ELIBEXEC], [:SystemCallError], [], []],
 [[:Errno, :ELIBBAD], [:SystemCallError], [], []],
 [[:Errno, :ELIBACC], [:SystemCallError], [], []],
 [[:Errno, :EL3RST], [:SystemCallError], [], []],
 [[:Errno, :EL3HLT], [:SystemCallError], [], []],
 [[:Errno, :EL2NSYNC], [:SystemCallError], [], []],
 [[:Errno, :EL2HLT], [:SystemCallError], [], []],
 [[:Errno, :EKEYREVOKED], [:SystemCallError], [], []],
 [[:Errno, :EKEYREJECTED], [:SystemCallError], [], []],
 [[:Errno, :EKEYEXPIRED], [:SystemCallError], [], []],
 [[:Errno, :EISNAM], [:SystemCallError], [], []],
 [[:Errno, :EISDIR], [:SystemCallError], [], []],
 [[:Errno, :EISCONN], [:SystemCallError], [], []],
 [[:Errno, :EIO], [:SystemCallError], [], []],
 [[:Errno, :EINVAL], [:SystemCallError], [], []],
 [[:Errno, :EINTR], [:SystemCallError], [], []],
 [[:Errno, :EINPROGRESS], [:SystemCallError], [], []],
 [[:Errno, :EILSEQ], [:SystemCallError], [], []],
 [[:Errno, :EIDRM], [:SystemCallError], [], []],
 [[:Errno, :EHWPOISON], [:SystemCallError], [], []],
 [[:Errno, :EHOSTUNREACH], [:SystemCallError], [], []],
 [[:Errno, :EHOSTDOWN], [:SystemCallError], [], []],
 [[:Errno, :EFBIG], [:SystemCallError], [], []],
 [[:Errno, :EFAULT], [:SystemCallError], [], []],
 [[:Errno, :EEXIST], [:SystemCallError], [], []],
 [[:Errno, :EDQUOT], [:SystemCallError], [], []],
 [[:Errno, :EDOTDOT], [:SystemCallError], [], []],
 [[:Errno, :EDOM], [:SystemCallError], [], []],
 [[:Errno, :EDESTADDRREQ], [:SystemCallError], [], []],
 [[:Errno, :EDEADLK], [:SystemCallError], [], []],
 [[:Errno, :ECONNRESET], [:SystemCallError], [], []],
 [[:Errno, :ECONNREFUSED], [:SystemCallError], [], []],
 [[:Errno, :ECONNABORTED], [:SystemCallError], [], []],
 [[:Errno, :ECOMM], [:SystemCallError], [], []],
 [[:Errno, :ECHRNG], [:SystemCallError], [], []],
 [[:Errno, :ECHILD], [:SystemCallError], [], []],
 [[:Errno, :ECANCELED], [:SystemCallError], [], []],
 [[:Errno, :EBUSY], [:SystemCallError], [], []],
 [[:Errno, :EBFONT], [:SystemCallError], [], []],
 [[:Errno, :EBADSLT], [:SystemCallError], [], []],
 [[:Errno, :EBADRQC], [:SystemCallError], [], []],
 [[:Errno, :EBADR], [:SystemCallError], [], []],
 [[:Errno, :EBADMSG], [:SystemCallError], [], []],
 [[:Errno, :EBADFD], [:SystemCallError], [], []],
 [[:Errno, :EBADF], [:SystemCallError], [], []],
 [[:Errno, :EBADE], [:SystemCallError], [], []],
 [[:Errno, :EALREADY], [:SystemCallError], [], []],
 [[:Errno, :EWOULDBLOCK], [:SystemCallError], [], []],
 [[:Errno, :EAGAIN], [:SystemCallError], [], []],
 [[:Errno, :EAFNOSUPPORT], [:SystemCallError], [], []],
 [[:Errno, :EADV], [:SystemCallError], [], []],
 [[:Errno, :EADDRNOTAVAIL], [:SystemCallError], [], []],
 [[:Errno, :EADDRINUSE], [:SystemCallError], [], []],
 [[:Errno, :EACCES], [:SystemCallError], [], []],
 [[:Errno, :E2BIG], [:SystemCallError], [], []],
 [[:Time], [:Object], [], []],
 [[:Dir], [:Object], [], []],
 [[:FileTest], [:Object], [], []],
 [[:IO], [:Object], [], []],
 [[:IO, :WaitWritable], [:Object], [], []],
 [[:IO, :WaitReadable], [:Object], [], []],
 [[:IO, :EINPROGRESSWaitWritable], [:Errno, :EINPROGRESS], [], []],
 [[:IO, :EINPROGRESSWaitReadable], [:Errno, :EINPROGRESS], [], []],
 [[:IO, :EAGAINWaitWritable], [:Errno, :EAGAIN], [], []],
 [[:IO, :EAGAINWaitReadable], [:Errno, :EAGAIN], [], []],
 [[:Warning], [:Object], [], []],
 [[:RuntimeError], [:StandardError], [], []],
 [[:FrozenError], [:RuntimeError], [], []],
 [[:ZeroDivisionError], [:StandardError], [], []],
 [[:ArgumentError], [:StandardError], [], []],
 [[:UncaughtThrowError], [:ArgumentError], [], []],
 [[:TypeError], [:StandardError], [], []],
 [[:ThreadError], [:StandardError], [], []],
 [[:SystemStackError], [:Exception], [], []],
 [[:SystemExit], [:Exception], [], []],
 [[:ScriptError], [:Exception], [], []],
 [[:SyntaxError], [:ScriptError], [], []],
 [[:IndexError], [:StandardError], [], []],
 [[:StopIteration], [:IndexError], [], []],
 [[:SignalException], [:Exception], [], []],
 [[:SecurityError], [:Exception], [], []],
 [[:RegexpError], [:StandardError], [], []],
 [[:RangeError], [:StandardError], [], []],
 [[:NotImplementedError], [:ScriptError], [], []],
 [[:NameError], [:StandardError], [], []],
 [[:NoMethodError], [:NameError], [], []],
 [[:NoMemoryError], [:Exception], [], []],
 [[:LocalJumpError], [:StandardError], [], []],
 [[:LoadError], [:ScriptError], [], []],
 [[:KeyError], [:IndexError], [], []],
 [[:IOError], [:StandardError], [], []],
 [[:Interrupt], [:SignalException], [], []],
 [[:FloatDomainError], [:RangeError], [], []],
 [[:EOFError], [:IOError], [], []],
 [[:ClosedQueueError], [:StopIteration], [], []],
 [[:Thread, :Queue], [:Object], [], []],
 [[:Thread, :SizedQueue], [:Thread, :Queue], [], []],
 [[:Thread, :Mutex], [:Object], [], []],
 [[:Thread, :ConditionVariable], [:Object], [], []],
 [[:Thread, :Backtrace], [:Object], [], []],
 [[:Thread, :Backtrace, :Location], [:Object], [], []],
 [[:GC], [:Object], [], []],
 [[:GC, :Profiler], [:Object], [], []],
 [[:TrueClass], [:Object], [[:!, [[[], [], nil, [:bool]]]]], []],
 [[:BigDecimal], [:Object], [], []],
 [[:MatchData], [:Object], [], []],
 [[:Symbol], [:Object], [], []],
 [[:Random], [:Object], [], []],
 [[:Random, :Formatter], [:Object], [], []],
 [[:Math],
  [:Object],
  [],
  [[:cos,
    [[[[:union,
        [[:instance, [:Integer]],
         [:instance, [:Float]],
         [:instance, [:Rational]],
         [:instance, [:BigDecimal]]]]],
      [],
      nil,
      [:instance, [:Float]]]]],
   [:sin,
    [[[[:union,
        [[:instance, [:Integer]],
         [:instance, [:Float]],
         [:instance, [:Rational]],
         [:instance, [:BigDecimal]]]]],
      [],
      nil,
      [:instance, [:Float]]]]],
   [:sqrt,
    [[[[:union,
        [[:instance, [:Integer]],
         [:instance, [:Float]],
         [:instance, [:Rational]],
         [:instance, [:BigDecimal]]]]],
      [],
      nil,
      [:instance, [:Float]]]]]]],
 [[:Math, :DomainError], [:StandardError], [], []],
 [[:File], [:IO], [], []],
 [[:File, :Stat], [:Object], [], []],
 [[:File, :Constants], [:Object], [], []],
 [[:UnboundMethod], [:Object], [], []],
 [[:Proc], [:Object], [], []],
 [[:Comparable], [:Object], [], []],
 [[:Float],
  [:Numeric],
  [[:!, [[[], [], nil, [:bool]]]],
   [:!=, [[[[:any]], [], nil, [:bool]]]],
   [:==, [[[[:any]], [], nil, [:bool]]]],
   [:__id__, [[[], [], nil, [:instance, [:Integer]]]]],
   [:__send__,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]]],
      [],
      nil,
      [:any]]]],
   [:equal?, [[[[:any]], [], nil, [:bool]]]],
   [:instance_eval,
    [[[[:instance, [:String]]],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:any]],
     [[], [], [[[:self]], [:any]], [:any]]]],
   [:instance_exec, [[[], [], [[], [:any]], [:any]]]],
   [:initialize, [[[], [], nil, [:any]]]],
   [:method_missing, [[[[:instance, [:Symbol]]], [], nil, [:any]]]],
   [:singleton_method_added, [[[[:instance, [:Symbol]]], [], nil, [:any]]]],
   [:singleton_method_removed, [[[[:instance, [:Symbol]]], [], nil, [:any]]]],
   [:singleton_method_undefined,
    [[[[:instance, [:Symbol]]], [], nil, [:any]]]],
   [:caller,
    [[[],
      [[:instance, [:Integer]], [:instance, [:Integer]]],
      nil,
      [:optional, [:instance, [:Array]]]],
     [[], [[:instance, [:Range]]], nil, [:optional, [:instance, [:Array]]]],
     [[], [], nil, [:instance, [:Array]]]]],
   [:caller_locations,
    [[[],
      [[:instance, [:Integer]], [:instance, [:Integer]]],
      nil,
      [:optional, [:instance, [:Array]]]],
     [[], [[:instance, [:Range]]], nil, [:optional, [:instance, [:Array]]]]]],
   [:catch,
    [[[[:any]], [], [[[:any]], [:any]], [:any]],
     [[], [], [[[:instance, [:Object]]], [:any]], [:any]]]],
   [:class, [[[], [], nil, [:any]]]],
   [:define_singleton_method,
    [[[[:instance, [:Symbol]],
       [:union, [[:instance, [:Method]], [:instance, [:UnboundMethod]]]]],
      [],
      nil,
      [:instance, [:Symbol]]],
     [[[:instance, [:Symbol]]], [], [[], [:any]], [:instance, [:Symbol]]]]],
   [:eval,
    [[[[:instance, [:String]]],
      [[:instance, [:Binding]],
       [:instance, [:String]],
       [:instance, [:Integer]]],
      nil,
      [:any]]]],
   [:iterator?, [[[], [], nil, [:bool]]]],
   [:local_variables, [[[], [], nil, [:instance, [:Array]]]]],
   [:srand, [[[], [[:instance, [:Numeric]]], nil, [:instance, [:Numeric]]]]],
   [:!~, [[[[:any]], [], nil, [:bool]]]],
   [:<=>,
    [[[[:instance, [:Numeric]]],
      [],
      nil,
      [:optional, [:instance, [:Integer]]]]]],
   [:===, [[[[:any]], [], nil, [:bool]]]],
   [:=~, [[[[:any]], [], nil, [:bool]]]],
   [:clone, [[[], [], nil, [:self]]]],
   [:display, [[[], [[:any]], nil, [:any]]]],
   [:dup, [[[], [], nil, [:self]]]],
   [:enum_for,
    [[[[:instance, [:Symbol]]],
      [],
      [[], [:instance, [:Integer]]],
      [:instance, [:Enumerator]]],
     [[], [], [[], [:instance, [:Integer]]], [:instance, [:Enumerator]]]]],
   [:eql?, [[[[:any]], [], nil, [:bool]]]],
   [:extend, [[[], [], nil, [:self]]]],
   [:fork,
    [[[], [], nil, [:optional, [:instance, [:Integer]]]],
     [[], [], [[], [:any]], [:optional, [:instance, [:Integer]]]]]],
   [:freeze, [[[], [], nil, [:self]]]],
   [:frozen?, [[[], [], nil, [:bool]]]],
   [:hash, [[[], [], nil, [:instance, [:Integer]]]]],
   [:initialize_copy, [[[[:self]], [], nil, [:self]]]],
   [:inspect, [[[], [], nil, [:instance, [:String]]]]],
   [:instance_of?, [[[[:instance, [:Module]]], [], nil, [:bool]]]],
   [:instance_variable_defined?,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]]],
      [],
      nil,
      [:bool]]]],
   [:instance_variable_get,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]]],
      [],
      nil,
      [:any]]]],
   [:instance_variable_set,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]], [:any]],
      [],
      nil,
      [:any]]]],
   [:instance_variables, [[[], [], nil, [:instance, [:Array]]]]],
   [:is_a?, [[[[:instance, [:Module]]], [], nil, [:bool]]]],
   [:method,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]]],
      [],
      nil,
      [:instance, [:Method]]]]],
   [:methods, [[[], [], nil, [:instance, [:Array]]]]],
   [:nil?, [[[], [], nil, [:bool]]]],
   [:private_methods, [[[], [], nil, [:instance, [:Array]]]]],
   [:protected_methods, [[[], [], nil, [:instance, [:Array]]]]],
   [:public_method,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      nil,
      [:instance, [:Method]]]]],
   [:public_methods, [[[], [[:bool]], nil, [:instance, [:Array]]]]],
   [:public_send,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      [[], [:any]],
      [:any]]]],
   [:remove_instance_variable,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      nil,
      [:any]]]],
   [:send,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      [[], [:any]],
      [:any]]]],
   [:singleton_class, [[[], [], nil, [:instance, [:Class]]]]],
   [:singleton_method,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      nil,
      [:instance, [:Method]]]]],
   [:singleton_methods, [[[], [], nil, [:instance, [:Array]]]]],
   [:taint, [[[], [], nil, [:self]]]],
   [:tainted?, [[[], [], nil, [:bool]]]],
   [:tap, [[[], [], [[[:self]], [:any]], [:self]]]],
   [:to_s, [[[], [], nil, [:instance, [:String]]]]],
   [:untaint, [[[], [], nil, [:self]]]],
   [:Array,
    [[[[:instance, [:NilClass]]], [], nil, [:array, [], [:union, []]]],
     [[[:instance, [:Array]]], [], nil, [:instance, [:Array]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Array]]],
     [[[:instance, [:Hash]]], [], nil, [:instance, [:Array]]],
     [[[:any]], [], nil, [:instance, [:Array]]]]],
   [:Complex,
    [[[[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      [[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      nil,
      [:instance, [:Complex]]]]],
   [:Float,
    [[[[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      [],
      nil,
      [:instance, [:Float]]]]],
   [:Hash, [[[[:instance, [:Object]]], [], nil, [:instance, [:Hash]]]]],
   [:Integer,
    [[[[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      [],
      nil,
      [:instance, [:Integer]]],
     [[[:instance, [:String]]],
      [[:instance, [:Integer]]],
      nil,
      [:instance, [:Integer]]]]],
   [:Rational,
    [[[[:union,
        [[:instance, [:Numeric]],
         [:instance, [:String]],
         [:instance, [:Object]]]]],
      [[:union, [[:instance, [:Numeric]], [:instance, [:String]]]]],
      nil,
      [:instance, [:Rational]]]]],
   [:String, [[[[:instance, [:Object]]], [], nil, [:instance, [:String]]]]],
   [:__callee__, [[[], [], nil, [:optional, [:instance, [:Symbol]]]]]],
   [:__dir__, [[[], [], nil, [:optional, [:instance, [:String]]]]]],
   [:__method__, [[[], [], nil, [:optional, [:instance, [:Symbol]]]]]],
   [:`, [[[[:instance, [:String]]], [], nil, [:instance, [:String]]]]],
   [:abort, [[[], [[:instance, [:String]]], nil, [:union, []]]]],
   [:at_exit, [[[], [], [[], [:any]], [:instance, [:Proc]]]]],
   [:autoload,
    [[[[:union, [[:instance, [:String]], [:instance, [:Symbol]]]],
       [:instance, [:String]]],
      [],
      nil,
      [:instance, [:NilClass]]]]],
   [:autoload?,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [],
      nil,
      [:optional, [:instance, [:String]]]]]],
   [:binding, [[[], [], nil, [:instance, [:Binding]]]]],
   [:exit,
    [[[], [], nil, [:union, []]],
     [[],
      [[:union,
        [[:instance, [:Integer]],
         [:instance, [:TrueClass]],
         [:instance, [:FalseClass]]]]],
      nil,
      [:union, []]]]],
   [:exit!,
    [[[[:union,
        [[:instance, [:Integer]],
         [:instance, [:TrueClass]],
         [:instance, [:FalseClass]]]]],
      [],
      nil,
      [:union, []]]]],
   [:fail,
    [[[], [], nil, [:union, []]],
     [[[:instance, [:String]]], [], nil, [:union, []]],
     [[],
      [[:instance, [:Exception]],
       [:instance, [:String]],
       [:instance, [:Array]]],
      nil,
      [:union, []]]]],
   [:format, [[[[:instance, [:String]]], [], nil, [:instance, [:String]]]]],
   [:gets,
    [[[],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:optional, [:instance, [:String]]]]]],
   [:global_variables, [[[], [], nil, [:instance, [:Array]]]]],
   [:load, [[[[:instance, [:String]]], [[:bool]], nil, [:bool]]]],
   [:loop,
    [[[], [], [[], [:any]], [:union, []]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:open,
    [[[[:instance, [:String]]],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:optional, [:instance, [:IO]]]],
     [[[:instance, [:String]]],
      [[:instance, [:String]], [:instance, [:Integer]]],
      [[[:instance, [:IO]]], [:any]],
      [:any]]]],
   [:print, [[[], [], nil, [:nil]]]],
   [:printf,
    [[[], [[:instance, [:IO]], [:instance, [:String]]], nil, [:nil]]]],
   [:proc, [[[], [], [[], [:any]], [:instance, [:Proc]]]]],
   [:lambda, [[[], [], [[], [:any]], [:instance, [:Proc]]]]],
   [:putc,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:String]]], [], nil, [:instance, [:String]]]]],
   [:puts, [[[], [], nil, [:instance, [:NilClass]]]]],
   [:p, [[[[:any]], [], nil, [:any]], [[], [], nil, [:instance, [:Array]]]]],
   [:pp, [[[[:any]], [], nil, [:any]], [[], [], nil, [:instance, [:Array]]]]],
   [:rand,
    [[[], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Integer]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Range]]], [], nil, [:instance, [:Float]]]]],
   [:readline,
    [[[],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:instance, [:String]]]]],
   [:readlines,
    [[[],
      [[:instance, [:String]], [:instance, [:Integer]]],
      nil,
      [:instance, [:Array]]]]],
   [:require, [[[[:instance, [:String]]], [], nil, [:bool]]]],
   [:require_relative, [[[[:instance, [:String]]], [], nil, [:bool]]]],
   [:select,
    [[[[:instance, [:Array]]],
      [[:instance, [:Array]], [:instance, [:Array]], [:instance, [:Integer]]],
      nil,
      [:instance, [:Array]]]]],
   [:sleep,
    [[[], [], nil, [:union, []]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Integer]]]]],
   [:syscall, [[[[:instance, [:Integer]]], [], nil, [:any]]]],
   [:test,
    [[[[:union, [[:instance, [:String]], [:instance, [:Integer]]]],
       [:union, [[:instance, [:String]], [:instance, [:IO]]]]],
      [[:union, [[:instance, [:String]], [:instance, [:IO]]]]],
      nil,
      [:union,
       [[:instance, [:TrueClass]],
        [:instance, [:FalseClass]],
        [:instance, [:Time]],
        [:nil],
        [:instance, [:Integer]]]]]]],
   [:throw, [[[[:instance, [:Object]]], [[:any]], nil, [:union, []]]]],
   [:warn, [[[], [], nil, [:instance, [:NilClass]]]]],
   [:exec, [[[], [], nil, [:union, []]]]],
   [:system,
    [[[],
      [],
      nil,
      [:union,
       [[:instance, [:NilClass]],
        [:instance, [:FalseClass]],
        [:instance, [:TrueClass]]]]]]],
   [:block_given?, [[[], [], nil, [:bool]]]],
   [:to_enum,
    [[[[:instance, [:Symbol]]],
      [],
      [[], [:instance, [:Integer]]],
      [:instance, [:Enumerator]]],
     [[], [], [[], [:instance, [:Integer]]], [:instance, [:Enumerator]]]]],
   [:kind_of?, [[[[:instance, [:Module]]], [], nil, [:bool]]]],
   [:untrust, [[[], [], nil, [:self]]]],
   [:untrusted?, [[[], [], nil, [:bool]]]],
   [:trust, [[[], [], nil, [:self]]]],
   [:raise,
    [[[], [], nil, [:union, []]],
     [[[:instance, [:String]]], [], nil, [:union, []]],
     [[],
      [[:instance, [:Exception]],
       [:instance, [:String]],
       [:instance, [:Array]]],
      nil,
      [:union, []]]]],
   [:sprintf, [[[[:instance, [:String]]], [], nil, [:instance, [:String]]]]],
   [:itself, [[[], [], nil, [:self]]]],
   [:object_id, [[[], [], nil, [:instance, [:Integer]]]]],
   [:respond_to?,
    [[[[:union, [[:instance, [:Symbol]], [:instance, [:String]]]]],
      [[:bool]],
      nil,
      [:bool]]]],
   [:yield_self,
    [[[], [], [[[:self]], [:any]], [:any]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:then,
    [[[], [], [[[:self]], [:any]], [:any]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:<, [[[[:instance, [:Numeric]]], [], nil, [:bool]]]],
   [:<=, [[[[:instance, [:Numeric]]], [], nil, [:bool]]]],
   [:>, [[[[:instance, [:Numeric]]], [], nil, [:bool]]]],
   [:>=, [[[[:instance, [:Numeric]]], [], nil, [:bool]]]],
   [:between?, [[[[:any], [:any]], [], nil, [:bool]]]],
   [:clamp, [[[[:any], [:any]], [], nil, [:any]]]],
   [:%,
    [[[[:instance, [:Integer]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Float]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Rational]]], [], nil, [:instance, [:Float]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Numeric]]]]],
   [:+@, [[[], [], nil, [:instance, [:Float]]]]],
   [:-@, [[[], [], nil, [:instance, [:Float]]]]],
   [:abs, [[[], [], nil, [:instance, [:Float]]]]],
   [:abs2, [[[], [], nil, [:instance, [:Float]]]]],
   [:angle,
    [[[],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:ceil,
    [[[], [], nil, [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:coerce,
    [[[[:instance, [:Numeric]]],
      [],
      nil,
      [:array,
       [[:instance, [:Numeric]], [:instance, [:Numeric]]],
       [:union, []]]]]],
   [:conj, [[[], [], nil, [:instance, [:Float]]]]],
   [:conjugate, [[[], [], nil, [:instance, [:Float]]]]],
   [:denominator, [[[], [], nil, [:instance, [:Integer]]]]],
   [:div, [[[[:instance, [:Numeric]]], [], nil, [:instance, [:Integer]]]]],
   [:divmod,
    [[[[:instance, [:Numeric]]],
      [],
      nil,
      [:array,
       [[:instance, [:Numeric]], [:instance, [:Numeric]]],
       [:union, []]]]]],
   [:fdiv,
    [[[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:finite?, [[[], [], nil, [:bool]]]],
   [:floor,
    [[[], [], nil, [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Numeric]]]]]]],
   [:i, [[[], [], nil, [:instance, [:Complex]]]]],
   [:imag, [[[], [], nil, [:instance, [:Integer]]]]],
   [:imaginary, [[[], [], nil, [:instance, [:Integer]]]]],
   [:infinite?, [[[], [], nil, [:optional, [:instance, [:Integer]]]]]],
   [:integer?, [[[], [], nil, [:bool]]]],
   [:modulo, [[[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:negative?, [[[], [], nil, [:bool]]]],
   [:nonzero?, [[[], [], nil, [:optional, [:self]]]]],
   [:numerator, [[[], [], nil, [:instance, [:Integer]]]]],
   [:polar,
    [[[],
      [],
      nil,
      [:array,
       [[:instance, [:Float]],
        [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]],
       [:union, []]]]]],
   [:positive?, [[[], [], nil, [:bool]]]],
   [:quo,
    [[[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:real, [[[], [], nil, [:instance, [:Float]]]]],
   [:real?, [[[], [], nil, [:true]]]],
   [:rect,
    [[[],
      [],
      nil,
      [:array,
       [[:instance, [:Float]], [:instance, [:Numeric]]],
       [:union, []]]]]],
   [:remainder, [[[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:round,
    [[[], [], nil, [:instance, [:Integer]]],
     [[[:union, [[:instance, [:Integer]], [:any]]]],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:step,
    [[[],
      [[:instance, [:Numeric]], [:instance, [:Numeric]]],
      [[[:instance, [:Float]]], [:any]],
      [:self]],
     [[],
      [[:instance, [:Numeric]], [:instance, [:Numeric]]],
      nil,
      [:instance, [:Enumerator]]],
     [[], [], [[[:instance, [:Float]]], [:any]], [:self]],
     [[], [], nil, [:instance, [:Enumerator]]]]],
   [:to_c, [[[], [], nil, [:instance, [:Complex]]]]],
   [:to_int, [[[], [], nil, [:instance, [:Integer]]]]],
   [:truncate,
    [[[], [], nil, [:instance, [:Integer]]],
     [[[:instance, [:Integer]]],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:zero?, [[[], [], nil, [:bool]]]],
   [:arg,
    [[[],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:magnitude, [[[], [], nil, [:instance, [:Float]]]]],
   [:phase,
    [[[],
      [],
      nil,
      [:union, [[:instance, [:Integer]], [:instance, [:Float]]]]]]],
   [:rectangular,
    [[[],
      [],
      nil,
      [:array,
       [[:instance, [:Float]], [:instance, [:Numeric]]],
       [:union, []]]]]],
   [:*,
    [[[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:**,
    [[[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:+,
    [[[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:-,
    [[[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:/,
    [[[[:instance, [:Complex]]], [], nil, [:instance, [:Complex]]],
     [[[:instance, [:Numeric]]], [], nil, [:instance, [:Float]]]]],
   [:nan?, [[[], [], nil, [:bool]]]],
   [:next_float, [[[], [], nil, [:instance, [:Float]]]]],
   [:prev_float, [[[], [], nil, [:instance, [:Float]]]]],
   [:rationalize,
    [[[], [[:instance, [:Numeric]]], nil, [:instance, [:Rational]]]]],
   [:to_f, [[[], [], nil, [:instance, [:Float]]]]],
   [:to_i, [[[], [], nil, [:instance, [:Integer]]]]],
   [:to_r, [[[], [], nil, [:instance, [:Rational]]]]]],
  []],
 [[:RubyVM], [:Object], [], []],
 [[:RubyVM, :InstructionSequence], [:Object], [], []]]
