#!/usr/bin/env ruby

require_relative "../lib/type-profiler"

rbs = nil
if File.extname(ARGV[0]) == ".rbs"
  rbs = ARGV.shift
end

if ARGV[0]
  iseq = TypeProfiler::ISeq.compile(ARGV[0])
else
  iseq = TypeProfiler::ISeq.compile_str($<.read)
end

TypeProfiler.type_profile(iseq, rbs)
