name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      id-token: write
      pull-requests: write
      issues: read
    environment:
      name: release
      deployment: false

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      - id: tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push gem
        if: steps.tagpr.outputs.tag != ''
        uses: rubygems/release-gem@v1
